export const cryptocurrencies = {
  '0x': 'zrx.v',
  '1inch Network': '1inch.v',
  Aave: 'aave.v',
  Algorand: 'algo.v',
  Amp: 'amp.v',
  Ankr: 'ankr.v',
  ApeCoin: 'ape3.v',
  Arweave: 'ar.v',
  Astar: 'astr.v',
  Audius: 'audio.v',
  Avalanche: 'avax.v',
  'Axie Infinity': 'axs.v',
  BORA: 'bora.v',
  Balancer: 'bal.v',
  'Basic Attention Token': 'bat.v',
  'Binance Coin': 'bnb.v',
  BinaryX: 'bnx.v',
  BitDAO: 'bit1.v',
  BitTorrent: 'btt.v',
  'Bitcoin Cash': 'bch.v',
  'Bitcoin Gold': 'btg.v',
  'Bitcoin SV': 'bsv.v',
  Bitcoin: 'btc.v',
  Cardano: 'ada.v',
  Celo: 'celo.v',
  Celsius: 'cel.v',
  Chain: 'xcn1.v',
  Chainlink: 'link.v',
  Chiliz: 'chz.v',
  Compound: 'comp1.v',
  'Convex Finance': 'cvx.v',
  Cosmos: 'atom.v',
  'Counos X': 'ccxx.v',
  'Crypto.com Coin': 'cro.v',
  'Curve DAO Token': 'crv.v',
  Dash: 'dash.v',
  DeFiChain: 'dfi.v',
  Decentraland: 'mana.v',
  Decred: 'dcr.v',
  Dogecoin: 'doge.v',
  'EOS-USD': 'eos.v',
  Elrond: 'egld.v',
  'Enjin Coin': 'enj.v',
  'Ethereum Classic': 'etc.v',
  'Ethereum Name Service': 'ens.v',
  Ethereum: 'eth.v',
  'FTX Token': 'ftt.v',
  Fantom: 'ftm.v',
  'Filecoin ': 'fil.v',
  Flow: 'flow.v',
  Frax: 'frax.v',
  Fruits: 'frts.v',
  Gala: 'gala.v',
  GateToken: 'gt.v',
  Gnosis: 'gno.v',
  Golem: 'glm.v',
  'Green Metaverse Token': 'gmt3.v',
  HEX: 'hex.v',
  Harmony: 'one1.v',
  Hedera: 'hbar.v',
  'Helium ': 'hnt.v',
  Hive: 'hive.v',
  Holo: 'hot1.v',
  Horizen: 'zen.v',
  'Huobi Token': 'ht.v',
  ICON: 'icx.v',
  IOST: 'iost.v',
  IOTA: 'miota.v',
  'Immutable X': 'imx1.v',
  'Internet Computer': 'icp.v',
  IoTeX: 'iotx.v',
  JUST: 'jst.v',
  Kadena: 'kda.v',
  Kava: 'kava.v',
  Klaytn: 'klay.v',
  'KuCoin Token': 'kcs.v',
  Kusama: 'ksm.v',
  'Kyber Network Crystal v2': 'knc.v',
  LINK: 'ln.v',
  'Lido stETH': 'steth.v',
  Liquity: 'lusd.v',
  Litecoin: 'ltc.v',
  Livepeer: 'lpt.v',
  LooksRare: 'looks.v',
  Loopring: 'lrc.v',
  MXC: 'mxc.v',
  Maker: 'mkr.v',
  Mina: 'mina.v',
  Monero: 'xmr.v',
  Moonbeam: 'glmr.v',
  'NEAR Protocol ': 'near.v',
  NEM: 'xem.v',
  NXM: 'nxm.v',
  Neo: 'neo.v',
  Neutrino: 'usdn.v',
  Nexo: 'nexo.v',
  OKB: 'okb.v',
  'OMG Network': 'omg.v',
  'Oasis Network': 'rose.v',
  Ontology: 'ont.v',
  Osmosis: 'osmo.v',
  'PAX Gold': 'paxg.v',
  PancakeSwap: 'cake.v',
  Polkadot: 'dot.v',
  Polygon: 'matic.v',
  Polymath: 'poly.v',
  Qtum: 'qtum.v',
  Quant: 'qnt.v',
  Ravencoin: 'rvn.v',
  'SHIBA INU': 'shib.v',
  'SKALE Network': 'skl.v',
  Safe: 'safe1.v',
  Serum: 'srm.v',
  'Siacoin ': 'sc.v',
  Solana: 'sol.v',
  Stacks: 'stx.v',
  Stellar: 'xlm.v',
  Storj: 'storj.v',
  Swipe: 'sxp.v',
  SwissBorg: 'chsb.v',
  Symbol: 'xym.v',
  Synthetix: 'snx.v',
  THETA: 'theta.v',
  THORChain: 'rune.v',
  TRON: 'trx.v',
  Terra: 'luna2.v',
  'Tether Gold': 'xaut.v',
  Tezos: 'xtz.v',
  'The Graph': 'grt1.v',
  'The Sandbox': 'sand.v',
  'The Transfer Token': 'ttt1.v',
  'Theta Fuel': 'tfuel.v',
  Threshold: 't.v',
  TitanSwap: 'titan.v',
  Toncoin: 'toncoin.v',
  'Trust Wallet Token': 'twt.v',
  'UNUS SED LEO': 'leo.v',
  Uniswap: 'uni1.v',
  VeChain: 'vet.v',
  WAX: 'waxp.v',
  WEMIX: 'wemix.v',
  'WOO Network': 'woo.v',
  Waves: 'waves.v',
  'XDC Network': 'xdc.v',
  XRP: 'xrp.v',
  Zcash: 'zec.v',
  Zilliqa: 'zil.v',
  eCash: 'xec.v',
  yOUcash: 'youc.v',
  'yearn.finance': 'yfi.v',
};
