export const cryptocurrencies = {
  "Bitcoin USD": "BTC-USD",
  "Ethereum USD": "ETH-USD",
  "Binance Coin USD": "BNB-USD",
  "XRP USD": "XRP-USD",
  "Cardano USD": "ADA-USD",
  "Solana USD": "SOL-USD",
  "Dogecoin USD": "DOGE-USD",
  "Polkadot USD": "DOT-USD",
  "HEX USD": "HEX-USD",
  "TRON USD": "TRX-USD",
  "SHIBA INU USD": "SHIB-USD",
  "UNUS SED LEO USD": "LEO-USD",
  "Avalanche USD": "AVAX-USD",
  "Polygon USD": "MATIC-USD",
  "yOUcash USD":"YOUC-USD",
  "Uniswap USD": "UNI1-USD",
  "Litecoin USD": "LTC-USD",
  "Lido stETH USD": "STETH-USD",
  "FTX Token USD": "FTT-USD",
  "Chainlink USD": "LINK-USD",
  "Stellar USD": "XLM-USD",
  "Crypto.com Coin USD": "CRO-USD",
  "NEAR Protocol USD	": "NEAR-USD",
  "Algorand USD": "ALGO-USD",
  "Cosmos USD": "ATOM-USD",
  "Monero USD": "XMR-USD",
  "Bitcoin Cash USD": "BCH-USD",
  "Ethereum Classic USD": "ETC-USD",
  "Chain USD": "XCN1-USD",
  "VeChain USD": "VET-USD",
  "Flow USD": "FLOW-USD",
  "Decentraland USD": "MANA-USD",
  "Hedera USD": "HBAR-USD",
  "Internet Computer USD": "ICP-USD",
  "THETA USD": "THETA-USD",
  "Elrond USD": "EGLD-USD",
  "Frax USD": "FRAX-USD",
  "Axie Infinity USD": "AXS-USD",
  "Toncoin USD": "TONCOIN-USD",
  "The Sandbox USD": "SAND-USD",
  "ApeCoin USD": "APE3-USD",
  "Tezos USD": "XTZ-USD",
  "Filecoin USD	": "FIL-USD",
  "Helium USD	": "HNT-USD",
  "Bitcoin SV USD": "BSV-USD",
  "KuCoin Token USD": "KCS-USD",
  "EOS-USD": "EOS USD",
  "Zcash USD": "ZEC-USD",
  "Maker USD": "MKR-USD",
  "Aave USD": "AAVE-USD",
  "IOTA USD": "MIOTA-USD",
  "Huobi Token USD": "HT-USD",
  "eCash USD": "XEC-USD",
  "Neutrino USD USD": "USDN-USD",
  "The Graph USD": "GRT1-USD",
  "OKB USD": "OKB-USD",
  "Liquity USD USD": "LUSD-USD",
  "THORChain USD": "RUNE-USD",
  "Klaytn USD": "KLAY-USD",
  "Fantom USD": "FTM-USD",
  "Waves USD": "WAVES-USD",
  "Neo USD": "NEO-USD",
  "Quant USD": "QNT-USD",
  "Basic Attention Token USD": "BAT-USD",
  "PAX Gold USD": "PAXG-USD",
  "Chiliz USD": "CHZ-USD",
  "Zilliqa USD": "ZIL-USD",
  "BitTorrent USD": "BTT-USD",
  "Loopring USD": "LRC-USD",
  "Dash USD": "DASH-USD",
  "Stacks USD": "STX-USD",
  "DeFiChain USD": "DFI-USD",
  "PancakeSwap USD": "CAKE-USD",
  "Green Metaverse Token USD": "GMT3-USD",
  "Enjin Coin USD": "ENJ-USD",
  "Kusama USD": "KSM-USD",
  "Tether Gold USD": "XAUT-USD",
  "Fruits USD": "FRTS-USD",
  "Curve DAO Token USD": "CRV-USD",
  "Gala USD": "GALA-USD",
  "Celo USD": "CELO-USD",
  "Amp USD": "AMP-USD",
  "Holo USD": "HOT1-USD",
  "Kava USD": "KAVA-USD",
  "1inch Network USD": "1INCH-USD",
  "Nexo USD": "NEXO-USD",
  "NEM USD": "XEM-USD",
  "Storj USD": "STORJ-USD",
  "XDC Network USD": "XDC-USD",
  "Safe USD": "SAFE1-USD",
  "Mina USD": "MINA-USD",
  "WEMIX USD": "WEMIX-USD",
  "Synthetix USD": "SNX-USD",
  "Decred USD": "DCR-USD",
  "Counos X USD": "CCXX-USD",
  "Arweave USD": "AR-USD",
  "GateToken USD": "GT-USD",
  "Kadena USD": "KDA-USD",
  "Qtum USD": "QTUM-USD",
  "Symbol USD": "XYM-USD",
  "Gnosis USD": "GNO-USD",
  "Compound USD": "COMP1-USD",
  "Threshold USD": "T-USD",
  "Bitcoin Gold USD": "BTG-USD",
  "Harmony USD": "ONE1-USD",
  "Convex Finance USD": "CVX-USD",
  "BORA USD": "BORA-USD",
  "Theta Fuel USD": "TFUEL-USD",
  "IOST USD": "IOST-USD",
  "OMG Network USD": "OMG-USD",
  "IoTeX USD": "IOTX-USD",
  "Audius USD": "AUDIO-USD",
  "Oasis Network USD": "ROSE-USD",
  "ICON USD": "ICX-USD",
  "BinaryX USD": "BNX-USD",
  "The Transfer Token USD": "TTT1-USD",
  "BitDAO USD": "BIT1-USD",
  "Kyber Network Crystal v2 USD": "KNC-USD",
  "TitanSwap USD": "TITAN-USD",
  "Ravencoin USD": "RVN-USD",
  "Ankr USD": "ANKR-USD",
  "Celsius USD": "CEL-USD",
  "0x USD": "ZRX-USD",
  "Trust Wallet Token USD": "TWT-USD",
  "NXM USD": "NXM-USD",
  "Osmosis USD": "OSMO-USD",
  "Serum USD": "SRM-USD",
  "Golem USD": "GLM-USD",
  "Terra USD": "LUNA2-USD",
  "WOO Network USD": "WOO-USD",
  "MXC USD": "MXC-USD",
  "LINK USD": "LN-USD",
  "Balancer USD": "BAL-USD",
  "JUST USD": "JST-USD",
  "Livepeer USD": "LPT-USD",
  "Ontology USD": "ONT-USD",
  "Swipe USD": "SXP-USD",
  "Siacoin USD	": "SC-USD",
  "SKALE Network USD": "SKL-USD",
  "WAX USD": "WAXP-USD",
  "yearn.finance USD": "YFI-USD",
  "Moonbeam USD": "GLMR-USD",
  "Immutable X USD": "IMX1-USD",
  "SwissBorg USD": "CHSB-USD",
  "Horizen USD": "ZEN-USD",
  "Ethereum Name Service USD": "ENS-USD",
  "Astar USD": "ASTR-USD",
  "LooksRare USD": "LOOKS-USD",
  "Hive USD": "HIVE-USD",
  "Polymath USD": "POLY-USD"
}