export const cryptocurrencies = {
  Bitcoin: 'BTC-USD',
  Ethereum: 'ETH-USD',
  'Binance Coin': 'BNB-USD',
  XRP: 'XRP-USD',
  Cardano: 'ADA-USD',
  Solana: 'SOL-USD',
  Dogecoin: 'DOGE-USD',
  Polkadot: 'DOT-USD',
  HEX: 'HEX-USD',
  TRON: 'TRX-USD',
  'SHIBA INU': 'SHIB-USD',
  'UNUS SED LEO': 'LEO-USD',
  Avalanche: 'AVAX-USD',
  Polygon: 'MATIC-USD',
  yOUcash: 'YOUC-USD',
  Uniswap: 'UNI1-USD',
  Litecoin: 'LTC-USD',
  'Lido stETH': 'STETH-USD',
  'FTX Token': 'FTT-USD',
  Chainlink: 'LINK-USD',
  Stellar: 'XLM-USD',
  'Crypto.com Coin': 'CRO-USD',
  'NEAR Protocol	': 'NEAR-USD',
  Algorand: 'ALGO-USD',
  Cosmos: 'ATOM-USD',
  Monero: 'XMR-USD',
  'Bitcoin Cash': 'BCH-USD',
  'Ethereum Classic': 'ETC-USD',
  Chain: 'XCN1-USD',
  VeChain: 'VET-USD',
  Flow: 'FLOW-USD',
  Decentraland: 'MANA-USD',
  Hedera: 'HBAR-USD',
  'Internet Computer': 'ICP-USD',
  THETA: 'THETA-USD',
  Elrond: 'EGLD-USD',
  Frax: 'FRAX-USD',
  'Axie Infinity': 'AXS-USD',
  Toncoin: 'TONCOIN-USD',
  'The Sandbox': 'SAND-USD',
  ApeCoin: 'APE3-USD',
  Tezos: 'XTZ-USD',
  'Filecoin	': 'FIL-USD',
  'Helium	': 'HNT-USD',
  'Bitcoin SV': 'BSV-USD',
  'KuCoin Token': 'KCS-USD',
  'EOS-USD': 'EOS',
  Zcash: 'ZEC-USD',
  Maker: 'MKR-USD',
  Aave: 'AAVE-USD',
  IOTA: 'MIOTA-USD',
  'Huobi Token': 'HT-USD',
  eCash: 'XEC-USD',
  Neutrino: 'USDN-USD',
  'The Graph': 'GRT1-USD',
  OKB: 'OKB-USD',
  Liquity: 'LUSD-USD',
  THORChain: 'RUNE-USD',
  Klaytn: 'KLAY-USD',
  Fantom: 'FTM-USD',
  Waves: 'WAVES-USD',
  Neo: 'NEO-USD',
  Quant: 'QNT-USD',
  'Basic Attention Token': 'BAT-USD',
  'PAX Gold': 'PAXG-USD',
  Chiliz: 'CHZ-USD',
  Zilliqa: 'ZIL-USD',
  BitTorrent: 'BTT-USD',
  Loopring: 'LRC-USD',
  Dash: 'DASH-USD',
  Stacks: 'STX-USD',
  DeFiChain: 'DFI-USD',
  PancakeSwap: 'CAKE-USD',
  'Green Metaverse Token': 'GMT3-USD',
  'Enjin Coin': 'ENJ-USD',
  Kusama: 'KSM-USD',
  'Tether Gold': 'XAUT-USD',
  Fruits: 'FRTS-USD',
  'Curve DAO Token': 'CRV-USD',
  Gala: 'GALA-USD',
  Celo: 'CELO-USD',
  Amp: 'AMP-USD',
  Holo: 'HOT1-USD',
  Kava: 'KAVA-USD',
  '1inch Network': '1INCH-USD',
  Nexo: 'NEXO-USD',
  NEM: 'XEM-USD',
  Storj: 'STORJ-USD',
  'XDC Network': 'XDC-USD',
  Safe: 'SAFE1-USD',
  Mina: 'MINA-USD',
  WEMIX: 'WEMIX-USD',
  Synthetix: 'SNX-USD',
  Decred: 'DCR-USD',
  'Counos X': 'CCXX-USD',
  Arweave: 'AR-USD',
  GateToken: 'GT-USD',
  Kadena: 'KDA-USD',
  Qtum: 'QTUM-USD',
  Symbol: 'XYM-USD',
  Gnosis: 'GNO-USD',
  Compound: 'COMP1-USD',
  Threshold: 'T-USD',
  'Bitcoin Gold': 'BTG-USD',
  Harmony: 'ONE1-USD',
  'Convex Finance': 'CVX-USD',
  BORA: 'BORA-USD',
  'Theta Fuel': 'TFUEL-USD',
  IOST: 'IOST-USD',
  'OMG Network': 'OMG-USD',
  IoTeX: 'IOTX-USD',
  Audius: 'AUDIO-USD',
  'Oasis Network': 'ROSE-USD',
  ICON: 'ICX-USD',
  BinaryX: 'BNX-USD',
  'The Transfer Token': 'TTT1-USD',
  BitDAO: 'BIT1-USD',
  'Kyber Network Crystal v2': 'KNC-USD',
  TitanSwap: 'TITAN-USD',
  Ravencoin: 'RVN-USD',
  Ankr: 'ANKR-USD',
  Celsius: 'CEL-USD',
  '0x': 'ZRX-USD',
  'Trust Wallet Token': 'TWT-USD',
  NXM: 'NXM-USD',
  Osmosis: 'OSMO-USD',
  Serum: 'SRM-USD',
  Golem: 'GLM-USD',
  Terra: 'LUNA2-USD',
  'WOO Network': 'WOO-USD',
  MXC: 'MXC-USD',
  LINK: 'LN-USD',
  Balancer: 'BAL-USD',
  JUST: 'JST-USD',
  Livepeer: 'LPT-USD',
  Ontology: 'ONT-USD',
  Swipe: 'SXP-USD',
  'Siacoin	': 'SC-USD',
  'SKALE Network': 'SKL-USD',
  WAX: 'WAXP-USD',
  'yearn.finance': 'YFI-USD',
  Moonbeam: 'GLMR-USD',
  'Immutable X': 'IMX1-USD',
  SwissBorg: 'CHSB-USD',
  Horizen: 'ZEN-USD',
  'Ethereum Name Service': 'ENS-USD',
  Astar: 'ASTR-USD',
  LooksRare: 'LOOKS-USD',
  Hive: 'HIVE-USD',
  Polymath: 'POLY-USD',
};
