
export const currencies = {
  "EUR/USD": "EURUSD=X",
  "USD/JPY": "JPY=X",
  "GBP/USD": "GBPUSD=X",
  "AUD/USD": "AUDUSD=X",
  "NZD/USD": "NZDUSD=X",
  "EUR/JPY": "EURJPY=X",
  "GBP/JPY": "GBPJPY=X",
  "EUR/GBP": "EURGBP=X",
  "EUR/CAD": "EURCAD=X",
  "EUR/SEK": "EURSEK=X",
  "EUR/CHF": "EURCHF=X",
  "EUR/HUF": "EURHUF=X",
  "USD/CNY": "CNY=X",
  "USD/HKD": "HKD=X",
  "USD/SGD": "SGD=X",
  "USD/INR": "INR=X",
  "USD/MXN": "MXN=X",
  "USD/PHP": "PHP=X",
  "USD/IDR": "IDR=X",
  "USD/THB": "THB=X",
  "USD/MYR": "IDR=X",
  "USD/ZAR": "ZAR=X",
  "USD/RUB": "RUB=X",
}