export const indices = [
  {
    name: 'Dow Jones',
    symbol: '^DJI',
    country: 'US',
    region: 'North America',
  },
  {
    name: 'NASDAQ 100',
    symbol: '^NDX',
    country: 'US',
    region: 'North America',
  },
  {
    name: 'NASDAQ Composite',
    symbol: '^IXIC',
    country: 'US',
    region: 'North America',
  },
  {
    name: 'S&P 500',
    symbol: '^GSPC',
    country: 'US',
    region: 'North America',
  },
  {
    name: 'CBOE Volatility',
    symbol: '^VIX',
    country: 'US',
    region: 'North America',
  },
  {
    name: 'US Dollar',
    symbol: 'DX-Y.NYB',
    country: 'US',
    region: 'North America',
  },
  {
    name: 'AEX',
    symbol: '^AEX',
    country: 'NL',
    region: 'Europe',
  },
  {
    name: 'CAC 40',
    symbol: '^FCH',
    country: 'FR',
    region: 'Europe',
  },
  {
    name: 'DAX',
    symbol: '^GDAXI',
    country: 'DE',
    region: 'Europe',
  },
  {
    name: 'Euro Stoxx 50',
    symbol: '^STOXX50E',
    country: 'DE',
    region: 'Europe',
  },
  {
    name: 'FTSE 100',
    symbol: '^FTSE',
    country: 'GB',
    region: 'Europe',
  },
  {
    name: 'FTSE MIB INDEX',
    symbol: 'FTSEMIB.MI',
    country: 'IT',
    region: 'Europe',
  },
  {
    name: 'IBEX 35',
    symbol: '^IBEX',
    country: 'ES',
    region: 'Europe',
  },
  {
    name: 'MOEX Russia',
    symbol: 'IMOEX.ME',
    country: 'RU',
    region: 'Europe',
  },
  {
    name: 'RTSI',
    symbol: 'RTSI.ME',
    country: 'RU',
    region: 'Europe',
  },
  {
    name: 'FTSE China A50',
    symbol: 'XIN9.FGI',
    country: 'CN',
    region: 'Asia',
  },
  {
    name: 'Hang Seng',
    symbol: '^HSI',
    country: 'CN',
    region: 'Asia',
  },
  {
    name: 'Nikkei 225',
    symbol: '^N225',
    country: 'JP',
    region: 'Asia',
  },
];
